function string = addText(Vec1, Vec2, Vec3)

string = strcat({'\leftarrow '}, ...
                num2str(Vec1(end)), {'; '}, ...
                num2str(Vec2(end)), {'; '}, ...
                num2str(Vec3(end)));
end